package org.romaframework.module.users.factory;

import org.romaframework.core.entity.EntityHelper;
import org.romaframework.core.factory.AbstractFactory;
import org.romaframework.module.users.domain.CustomProfiling;

/**
 * Factory class for CustomProfiling entity. It's registered in the IoC configuration files and is used by Roma components to create objects of kind CustomProfiling. 
 * <br/>Use EntityHelper.createObject() to create objects using the its factory.
 * <br/>This class was generated by Roma Meta Framework CRUD wizard.
 * @see EntityHelper  
 */ 
public class CustomProfilingFactory extends AbstractFactory<CustomProfiling> {
  @Override
  public CustomProfiling create() {
    return new CustomProfiling();
  }
}
