package org.romaframework.module.users.repository;

import org.romaframework.core.repository.PersistenceAspectRepository;
import org.romaframework.module.users.domain.BaseGroup;

/**
 * Repository class for BaseGroup entity. By default it extends the PersistenceAspectRepository class that delegates the execution
 * of all commands to the PersistenceAspect. <br/>
 * <br/>
 * This class was generated by Roma Meta Framework CRUD wizard.
 */
public class BaseGroupRepository extends PersistenceAspectRepository<BaseGroup> {
}
